name: Copy Docker Image
run-name: Copy ${{ inputs.source_repo }} to ${{ inputs.destination_repo }}
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-shanghai.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      platforms:
        description: '平台 (默认 -a 全平台；指定格式 linux/amd64 linux/arm64)'
        required: false
        default: '-a'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Copy Docker Images
      shell: bash
      env:
        SOURCE: ${{ github.event.inputs.source }}
        SOURCE_CREDENTIAL: ${{ secrets.SOURCE_CREDENTIAL }}
        DESTINATION: ${{ github.event.inputs.destination }}
        DESTINATION_CREDENTIAL: ${{ secrets.DESTINATION_CREDENTIAL }}
        PLATFORMS: ${{ github.event.inputs.platforms }}
        COPY: "${{ github.event.inputs.source_repo }} ${{ github.event.inputs.destination_repo }}"
      run: bash .github/scripts/docker-sync.sh
